### ISSUE TITLE
Coil is not rendering any thing even the logger show Successful

### ISSUE THREAD

**Issue by 658jjh** [coil-kt/coil#2748]
**Describe the bug**
I am using Kotlin Compose for Android. Just use a normal function to show an URL image like this:

```
AsyncImage(
    model = "URL string",
    contentDescription = null,
    placeholder = placeholder,
    error = error
)
```

and my ImageLoader:

```
  @Provides
    @Singleton
    fun imageLoader(
        @ApplicationContext application: Context,
    ): ImageLoader = trace("WallingImageLoader") {
        ImageLoader.Builder(application)
            .components {
                add(SvgDecoder.Factory())
                add(
                    OkHttpNetworkFetcherFactory(
                        callFactory = {
                            OkHttpClient()
                        },
                    ),
                )
            }
            .crossfade(true)
            .apply {
                if (BuildConfig.DEBUG) {
                    logger(DebugLogger())
                }
            }
            .build()
    }
```
it just show the placeholder a bit (I guess it loading the image) the it show a blank. And the log show 
`💾 Successful (DISK)`

**Version**
**3.0.4**

**Comment by colinrtwhite** [comment]
There isn't enough information here to reproduce the issue. Can you create a small sample that reproduces the issue?

**Comment by wuujcik** [comment]
I have a similar situation, but with Ktor (Kotlin multiplatform) after upgrading Kotlin to 2.0.21 and multiplatform compose to 1.7.1. The url that used to work, currently doesn't.

coil3-coil = "3.0.4"
ktor = "3.0.2"

coil3-coil = {module = "io.coil-kt.coil3:coil", version.ref = "coil3-coil" }
coil3-compose = {module = "io.coil-kt.coil3:coil-compose", version.ref = "coil3-coil" }
coil3-network = {module = "io.coil-kt.coil3:coil-network-ktor2", version.ref = "coil3-coil" }

```
AsyncImage(
    model = backgroundImageUrl,
    contentDescription = null,
    modifier = Modifier.fillMaxSize(),
    contentScale = ContentScale.Crop
)
```
and this is stracktrace:    
```
🚨 Failed - https://my.image.url.that.worked.before.I.upgraded.to.kotlin.2.0.21.and.jetpack.1.7.1
java.lang.NoClassDefFoundError: Failed resolution of: Lio/ktor/utils/io/jvm/nio/WritingKt;
                                           	at coil3.network.ktor2.internal.Utils_jvmCommonKt.writeTo(utils.jvmCommon.kt:18)
                                           	at coil3.network.ktor2.internal.KtorNetworkResponseBody.writeTo-impl(utils.kt:89)
                                           	at coil3.network.ktor2.internal.KtorNetworkResponseBody.writeTo(utils.kt:88)
                                           	at coil3.network.NetworkFetcher.writeToDiskCache(NetworkFetcher.kt:153)
                                           	at coil3.network.NetworkFetcher.access$writeToDiskCache(NetworkFetcher.kt:32)
                                           	at coil3.network.NetworkFetcher$fetch$fetchResult$1.invokeSuspend(NetworkFetcher.kt:76)
                                           	at coil3.network.NetworkFetcher$fetch$fetchResult$1.invoke(Unknown Source:8)
                                           	at coil3.network.NetworkFetcher$fetch$fetchResult$1.invoke(Unknown Source:4)
                                           	at coil3.network.NetworkFetcher$executeNetworkRequest$2.invokeSuspend(NetworkFetcher.kt:204)
                                           	at coil3.network.NetworkFetcher$executeNetworkRequest$2.invoke(Unknown Source:8)
                                           	at coil3.network.NetworkFetcher$executeNetworkRequest$2.invoke(Unknown Source:4)
                                           	at coil3.network.ktor2.internal.KtorNetworkClient$executeRequest$2.invokeSuspend(utils.kt:35)
                                           	at coil3.network.ktor2.internal.KtorNetworkClient$executeRequest$2.invoke(Unknown Source:8)
                                           	at coil3.network.ktor2.internal.KtorNetworkClient$executeRequest$2.invoke(Unknown Source:4)
                                           	at io.ktor.client.statement.HttpStatement.execute(HttpStatement.kt:52)
                                           	at io.ktor.client.statement.HttpStatement$execute$1.invokeSuspend(Unknown Source:15)
                                           	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                           	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101)
                                           	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:113)
                                           	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89)
                                           	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:589)
                                           	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:823)
                                           	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:720)
                                           	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:707)
                                           Caused by: java.lang.ClassNotFoundException: Didn't find class "io.ktor.utils.io.jvm.nio.WritingKt" on path: DexPathList[[dex file "/data/data/com.spaceti.meetingroom.debug/code_cache/.overlay/base.apk/classes17.dex", dex file "/data/data/com.spaceti.meetingroom.debug/code_cache/.overlay/base.apk/classes13.dex", dex file "/data/data/com.spaceti.meetingroom.debug/code_cache/.overlay/base.apk/classes15.dex", dex file "/data/data/com.spaceti.meetingroom.debug/code_cache/.overlay/base.apk/classes8.dex", dex file "/data/data/com.spaceti.meetingroom.debug/code_cache/.overlay/base.apk/classes9.dex", dex file "/data/data/com.spaceti.meetingroom.debug/code_cache/.overlay/base.apk/classes.dex", dex file "/data/data/com.spaceti.meetingroom.debug/code_cache/.overlay/base.apk/classes20.dex", zip file "/data/app/~~oi_LemwJkd12HjWOL_yL9g==/com.spaceti.meetingroom.debug-k__cGfa7afw_18Pq0_GFUQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~oi_LemwJkd12HjWOL_yL9g==/com.spaceti.meetingroom.debug-k__cGfa7afw_18Pq0_GFUQ==/lib/arm64, /data/app/~~oi_LemwJkd12HjWOL_yL9g==/com.spaceti.meetingroom.debug-k__cGfa7afw_18Pq0_GFUQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
                                           	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
                                           	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                                           	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                           	at coil3.network.ktor2.internal.Utils_jvmCommonKt.writeTo(utils.jvmCommon.kt:18) 
                                           	at coil3.network.ktor2.internal.KtorNetworkResponseBody.writeTo-impl(utils.kt:89) 
                                           	at coil3.network.ktor2.internal.KtorNetworkResponseBody.writeTo(utils.kt:88) 
                                           	at coil3.network.NetworkFetcher.writeToDiskCache(NetworkFetcher.kt:153) 
                                           	at coil3.network.NetworkFetcher.access$writeToDiskCache(NetworkFetcher.kt:32) 
                                           	at coil3.network.NetworkFetcher$fetch$fetchResult$1.invokeSuspend(NetworkFetcher.kt:76) 
                                           	at coil3.network.NetworkFetcher$fetch$fetchResult$1.invoke(Unknown Source:8) 
                                           	at coil3.network.NetworkFetcher$fetch$fetchResult$1.invoke(Unknown Source:4) 
                                           	at coil3.network.NetworkFetcher$executeNetworkRequest$2.invokeSuspend(NetworkFetcher.kt:204) 
                                           	at coil3.network.NetworkFetcher$executeNetworkRequest$2.invoke(Unknown Source:8) 
                                           	at coil3.network.NetworkFetcher$executeNetworkRequest$2.invoke(Unknown Source:4) 
                                           	at coil3.network.ktor2.internal.KtorNetworkClient$executeRequest$2.invokeSuspend(utils.kt:35) 
                                           	at coil3.network.ktor2.internal.KtorNetworkClient$executeRequest$2.invoke(Unknown Source:8) 
                                           	at coil3.network.ktor2.internal.KtorNetworkClient$executeRequest$2.invoke(Unknown Source:4) 
                                           	at io.ktor.client.statement.HttpStatement.execute(HttpStatement.kt:52) 
                                           	at io.ktor.client.statement.HttpStatement$execute$1.invokeSuspend(Unknown Source:15) 
                                           	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) 
                                           	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101) 
                                           	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:113) 
                                           	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89) 
                                           	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:589) 
                                           	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:823) 
                                           	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:720) 
                                           	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:707) 
```

**Comment by wuujcik** [comment]
I have a similar situation, but with Ktor (Kotlin multiplatform) after upgrading Kotlin to 2.0.21 and multiplatform compose to 1.7.1. The url that used to work, currently doesn't.

coil3-coil = "3.0.4"
ktor = "3.0.2"

coil3-coil = {module = "io.coil-kt.coil3:coil", version.ref = "coil3-coil" }
coil3-compose = {module = "io.coil-kt.coil3:coil-compose", version.ref = "coil3-coil" }
coil3-network = {module = "io.coil-kt.coil3:coil-network-ktor2", version.ref = "coil3-coil" }

```
AsyncImage(
    model = backgroundImageUrl,
    contentDescription = null,
    modifier = Modifier.fillMaxSize(),
    contentScale = ContentScale.Crop
)
```
and this is stracktrace:    
```
🚨 Failed - https://my.image.url.that.worked.before.I.upgraded.to.kotlin.2.0.21.and.jetpack.1.7.1
java.lang.NoClassDefFoundError: Failed resolution of: Lio/ktor/utils/io/jvm/nio/WritingKt;
                                           	at coil3.network.ktor2.internal.Utils_jvmCommonKt.writeTo(utils.jvmCommon.kt:18)
                                           	at coil3.network.ktor2.internal.KtorNetworkResponseBody.writeTo-impl(utils.kt:89)
                                           	at coil3.network.ktor2.internal.KtorNetworkResponseBody.writeTo(utils.kt:88)
                                           	at coil3.network.NetworkFetcher.writeToDiskCache(NetworkFetcher.kt:153)
                                           	at coil3.network.NetworkFetcher.access$writeToDiskCache(NetworkFetcher.kt:32)
                                           	at coil3.network.NetworkFetcher$fetch$fetchResult$1.invokeSuspend(NetworkFetcher.kt:76)
                                           	at coil3.network.NetworkFetcher$fetch$fetchResult$1.invoke(Unknown Source:8)
                                           	at coil3.network.NetworkFetcher$fetch$fetchResult$1.invoke(Unknown Source:4)
                                           	at coil3.network.NetworkFetcher$executeNetworkRequest$2.invokeSuspend(NetworkFetcher.kt:204)
                                           	at coil3.network.NetworkFetcher$executeNetworkRequest$2.invoke(Unknown Source:8)
                                           	at coil3.network.NetworkFetcher$executeNetworkRequest$2.invoke(Unknown Source:4)
                                           	at coil3.network.ktor2.internal.KtorNetworkClient$executeRequest$2.invokeSuspend(utils.kt:35)
                                           	at coil3.network.ktor2.internal.KtorNetworkClient$executeRequest$2.invoke(Unknown Source:8)
                                           	at coil3.network.ktor2.internal.KtorNetworkClient$executeRequest$2.invoke(Unknown Source:4)
                                           	at io.ktor.client.statement.HttpStatement.execute(HttpStatement.kt:52)
                                           	at io.ktor.client.statement.HttpStatement$execute$1.invokeSuspend(Unknown Source:15)
                                           	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                           	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101)
                                           	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:113)
                                           	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89)
                                           	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:589)
                                           	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:823)
                                           	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:720)
                                           	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:707)
                                           Caused by: java.lang.ClassNotFoundException: Didn't find class "io.ktor.utils.io.jvm.nio.WritingKt" on path: DexPathList[[dex file "/data/data/com.company.app.debug/code_cache/.overlay/base.apk/classes17.dex", dex file "/data/data/com.company.app.debug/code_cache/.overlay/base.apk/classes13.dex", dex file "/data/data/com.company.app.debug/code_cache/.overlay/base.apk/classes15.dex", dex file "/data/data/com.company.app.debug/code_cache/.overlay/base.apk/classes8.dex", dex file "/data/data/com.company.app.debug/code_cache/.overlay/base.apk/classes9.dex", dex file "/data/data/com.company.app.debug/code_cache/.overlay/base.apk/classes.dex", dex file "/data/data/com.company.app.debug/code_cache/.overlay/base.apk/classes20.dex", zip file "/data/app/~~oi_LemwJkd12HjWOL_yL9g==/com.company.app.debug-k__cGfa7afw_18Pq0_GFUQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~oi_LemwJkd12HjWOL_yL9g==/com.company.app.debug-k__cGfa7afw_18Pq0_GFUQ==/lib/arm64, /data/app/~~oi_LemwJkd12HjWOL_yL9g==/com.company.app.debug-k__cGfa7afw_18Pq0_GFUQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
                                           	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
                                           	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                                           	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                           	at coil3.network.ktor2.internal.Utils_jvmCommonKt.writeTo(utils.jvmCommon.kt:18) 
                                           	at coil3.network.ktor2.internal.KtorNetworkResponseBody.writeTo-impl(utils.kt:89) 
                                           	at coil3.network.ktor2.internal.KtorNetworkResponseBody.writeTo(utils.kt:88) 
                                           	at coil3.network.NetworkFetcher.writeToDiskCache(NetworkFetcher.kt:153) 
                                           	at coil3.network.NetworkFetcher.access$writeToDiskCache(NetworkFetcher.kt:32) 
                                           	at coil3.network.NetworkFetcher$fetch$fetchResult$1.invokeSuspend(NetworkFetcher.kt:76) 
                                           	at coil3.network.NetworkFetcher$fetch$fetchResult$1.invoke(Unknown Source:8) 
                                           	at coil3.network.NetworkFetcher$fetch$fetchResult$1.invoke(Unknown Source:4) 
                                           	at coil3.network.NetworkFetcher$executeNetworkRequest$2.invokeSuspend(NetworkFetcher.kt:204) 
                                           	at coil3.network.NetworkFetcher$executeNetworkRequest$2.invoke(Unknown Source:8) 
                                           	at coil3.network.NetworkFetcher$executeNetworkRequest$2.invoke(Unknown Source:4) 
                                           	at coil3.network.ktor2.internal.KtorNetworkClient$executeRequest$2.invokeSuspend(utils.kt:35) 
                                           	at coil3.network.ktor2.internal.KtorNetworkClient$executeRequest$2.invoke(Unknown Source:8) 
                                           	at coil3.network.ktor2.internal.KtorNetworkClient$executeRequest$2.invoke(Unknown Source:4) 
                                           	at io.ktor.client.statement.HttpStatement.execute(HttpStatement.kt:52) 
                                           	at io.ktor.client.statement.HttpStatement$execute$1.invokeSuspend(Unknown Source:15) 
                                           	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) 
                                           	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101) 
                                           	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:113) 
                                           	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89) 
                                           	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:589) 
                                           	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:823) 
                                           	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:720) 
                                           	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:707) 
```

**Comment by wuujcik** [comment]
I found my issue - I upgraded Ktor to 3.x but didn't change Coil network library, after updating to coil3-network = {module = "io.coil-kt.coil3:coil-network-ktor3", version.ref = "coil3-coil" } it works.

**Comment by colinrtwhite** [comment]
Please reopen with a reproduction case.
